@Base_URL=http://localhost:8808/api
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MmM2YjlkYy05NmJiLTRiM2QtOTliNS05NDcyNWQ4NzJiZjMiLCJsaW5lVXNlcklkIjoiVTJiNDkyMDgxMGYxMDYxYzEwMWUyYWU3NWQ1ZDhmYTYzIiwiZGlzcGxheU5hbWUiOiJwYXNpdCIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vcHJvZmlsZS5saW5lLXNjZG4ubmV0LzBoLWwycDZiYTVja01mQ1cxMTFQY01mVzlaY1NrOGVDdFJZMjlwSWk1Y0tYQXFiREVkTlQ4X0lDTmFLeWNxTURFVFptYzZMSGhlTFhvOVdreGdOeHBLVFgxeFZoTkxiWDFvTW1wVlFtTUlRbmRtY1ZRU1hTdFpmMjV6S1FWQVJ6QVFaeHhUWDJOclhBbEJmbnhEVVRGaFdYSVZTQ3RXVUZ4IiwiaWF0IjoxNzg5MzE2MjQwLCJleHAiOjE3OTA1MjU4NDB9.DA-BC1bL7pYM8idp9R16ZFkAZAkG34aYqBen7gO7704
@LineUserId=U2b4920810f1061c101e2ae75d5d8fa63
@UserId=82c6b9dc-96bb-4b3d-99b5-94725d872bf3
@BillId=a763074f-c793-48bf-8937-2cadaf58cf36


@Token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OWVhZGI1MC0xMjQ0LTQ4ZDgtOTBkYS1iMDE1NmJmNTYxNmMiLCJsaW5lVXNlcklkIjoiVEVTVC1VU0VSLTAxMCIsImRpc3BsYXlOYW1lIjoiQm9iYnkxMCIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vZXhhbXBsZTIuY29tL2F2YXRhci5wbmciLCJpYXQiOjE3ODkzMTYwNjYsImV4cCI6MTc5MDUyNTY2Nn0.fTTS76n-PIpA_AYIScthMXVDdHIR5mKLBUkBTo746Dc
@LineUserId2=TEST-USER-010
@UserId2=59eadb50-1244-48d8-90da-b0156bf5616c

@Token3=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjA2YTYyNS02NzRjLTRmNzQtYTk2My0yYTlhYTVkNTg4M2IiLCJsaW5lVXNlcklkIjoiVEVTVC1VU0VSLTAxMSIsImRpc3BsYXlOYW1lIjoiQm9iYnkxMSIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vZXhhbXBsZTIuY29tL2F2YXRhci5wbmciLCJpYXQiOjE3ODkzMTYzMzAsImV4cCI6MTc5MDUyNTkzMH0.sWAfOWpa9RLorFVnNdKYDuFA_X1dHvUEIyX09Zj4I_0
@LineUserId3=TEST-USER-011
@UserId3=6206a625-674c-4f74-a963-2a9aa5d5883b


@PaymentSlipId=3062d70e-e914-4610-90c3-964edf5cb1bf


### Test Api
GET http://localhost:8808


### Register-Line   POST/auth/test-register
POST {{Base_URL}}/auth/test-register
Content-Type: application/json

{
  "lineUserId":"TEST-USER-011",
  "displayName":"Bobby11",
  "profileImage":"https://example2.com/avatar.png",
  "email":"Addy11@mail.com",
  "birthDay":"1995-09-06",
  "qrPayment":"",
  "promptpay":"0023456711"
}

### Test Login   POST/auth/test-login
POST {{Base_URL}}/auth/test-login
Content-Type: application/json

{
  "lineUserId":"{{LineUserId}}"
}


### Create Bill  POST/bills
POST {{Base_URL}}/bills/
Authorization: Bearer {{Token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="billName"

Test Restaurant
--boundary
Content-Disposition: form-data; name="receiptFile"; filename="Receipt.png"
Content-Type: image/png

< C:\Pasit\CCW1\WongLao\Backend\uploads\receipts\Receipt.png
--boundary--



###  OCR Receipt xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx not use xxxxxxxxxxxx
POST {{Base_URL}}/ocr/receipt
Content-Type: application/json

{
    "imagePath":"./uploads/receipts/Receipt.png"
}

### OCR Seve Bill status Checking   xxxxxxxxxxxxxxxx not use xxxxxxxxxxxx
POST {{Base_URL}}/ocr/bill/{{BillId}}
Content-Type: application/json

{"shopName": "บริษัท ร้านอาหาร จำกัด",
    "branch": "สาขา 00001",
    "receiptNumber": "ธ12-67-0119-00001",
    "date": "14/3/2566",
    "time": "20:36:32",
    "customerName": "เอกวัฒน์ ปูคำ",
    "items": [
      {
        "name": "ผัดเผ็ดเนื้อ",
        "quantity": 1,
        "unitPrice": 189,
        "totalPrice": 189
      },
      {
        "name": "ปลาทอดน้ำปลา",
        "quantity": 1,
        "unitPrice": 249,
        "totalPrice": 249
      },
      {
        "name": "ปลาทับทิมเพิ่ม",
        "quantity": 1,
        "unitPrice": 50,
        "totalPrice": 50
      },
      {
        "name": "ต้มยำทะเลรวม",
        "quantity": 1,
        "unitPrice": 249,
        "totalPrice": 249
      },
      {
        "name": "แสงโสม (กลม)",
        "quantity": 1,
        "unitPrice": 389,
        "totalPrice": 389
      },
      {
        "name": "น้ำเปล่า",
        "quantity": 2,
        "unitPrice": 20,
        "totalPrice": 40
      },
      {
        "name": "โซดา",
        "quantity": 2,
        "unitPrice": 29,
        "totalPrice": 58
      },
      {
        "name": "น้ำแข็ง",
        "quantity": 1,
        "unitPrice": 29,
        "totalPrice": 29
      },
      {
        "name": "เอ็นไก่ทอด 1+1",
        "quantity": 2,
        "unitPrice": null,
        "totalPrice": 129
      }
    ],
    "subtotal": 1382,
    "vat": 103.56,
    "totalAmount": 1583
}


### OCR Bill by billId        POST/ocr/bill/:billId
POST {{Base_URL}}/ocr/bill/{{BillId}}
Authorization: Bearer {{Token}}

### Verify bill           PUT/bills/:billId/verify
PUT {{Base_URL}}/bills/{{BillId}}/verify
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "shopName": "บริษัท ร้านอาหาร จำกัด",
  "totalAmount": 1583
}

### JoinBill        POST/jbill/:billId/join
POST {{Base_URL}}/jbill/{{BillId}}/join
Authorization: Bearer {{Token3}}


### Get Bill for join
GET {{Base_URL}}/jbill/{{BillId}}/join
Authorization: Bearer {{Token}}



### PATCH selected Split-method      PATCH/split/:billId/split-method
PATCH {{Base_URL}}/split/{{BillId}}/split-method
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "splitMethod":"EQUAL"
}

#########################################################################
@BillId_1=8af622c3-510b-4171-a237-a94cb19add60

### Select share-method
POST {{Base_URL}}/split/{{BillId_1}}/equal
Authorization: Bearer {{Token}}

### Get my payment/me       GET/payment/:billId/me
GET {{Base_URL}}/payment/{{BillId_1}}/me
Authorization: Bearer {{Token}}


### Upload Payment Slip
POST {{Base_URL}}/payment/{{BillId_3}}/slip
Authorization: Bearer {{Token}}
Content-Type: multipart/form-data; boundary=----WongLaoBoundary

------WongLaoBoundary
Content-Disposition: form-data; name="proofImage"; filename="slip.jpg"
Content-Type: image/jpeg

< C:\Pasit\CCW1\WongLao\Backend\uploads\slip\09435DA7-D68D-4FCD-8485-FD18D8788A57.jpg
------WongLaoBoundary--

### Get Pending Payment Slips    GET/payment/:billId/pending
GET {{Base_URL}}/payment/{{BillId_1}}/pending
Authorization: Bearer {{Token}}


###GET All bill UnPaid
GET {{Base_URL}}/payment/summary?page=1&limit=5
Authorization: Bearer {{Token}}

### Verify Payment Slip
PATCH {{Base_URL}}/payment/slip/{{PaymentSlipId}}/verify
Authorization: Bearer {{Token}}

############################################################

@BillId_2=a763074f-c793-48bf-8937-2cadaf58cf36

### PATCH selected Split-method      PATCH/split/:billId/split-method
PATCH {{Base_URL}}/split/{{BillId_2}}/split-method
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "splitMethod":"PROPORTIONAL"
}

### PATCH selected split food   PATCH/foodsplit/:billId/
PATCH {{Base_URL}}/foodsplit/{{BillId_2}}
Authorization: Bearer {{Token3}}
Content-Type: application/json

{
  "selections":[
    {
            "billItemId": "03171a6f-b3f6-4719-90b2-1a9b4214fc9e",
            "eating": true
        },
        {
            "billItemId": "3a832766-12f7-4c43-adee-cd238c05dbd4",
            "eating": true
        },
        {
            "billItemId": "4a2191b1-b0f9-4ff5-b973-a4f80b0084af",
            "eating": false
        },
        {
            "billItemId": "724ebb90-400f-43d0-a1bd-220dc9dc5e9e",
            "eating": false
        },
        {
            "billItemId": "7590d357-dc98-4b3e-9e2f-3bf412f8088a",
            "eating": false
        },
        {
            "billItemId": "8f03e1c1-804a-45e0-b683-5bde9d0dd418",
            "eating": true
        },
        {
            "billItemId": "c0335aae-bb38-4903-9c5b-76db9c5667ce",
            "eating": false
        },
        {
            "billItemId": "d121986a-c5b2-4a42-a7e4-64885837069e",
            "eating": false
        },
        {
            "billItemId": "e9105158-e110-4388-9f0a-a2b57d3d34a4",
            "eating": true
        }
  ]
}

#### POST Cal share food          POST/foodsplit/:BillId/caluculate
POST {{Base_URL}}/foodsplit/{{BillId_2}}/calculate
Authorization: Bearer {{Token}}


### GET amount pay for split-food
GET {{Base_URL}}/foodsplit/{{BillId_2}}/me
Authorization: Bearer {{Token}}

### GET food from split-food
GET {{Base_URL}}/foodsplit/{{BillId_2}}/eatMe
Authorization: Bearer {{Token}}


##############################################################

@BillId_3=48377e3b-7698-46a5-90e3-cacd0639d9a7
@BillmemberId_1=9c8159d9-72b2-4863-ba0b-1b89bef17927
@BillmemberId_2=edb729ae-0095-40fa-974d-ef6f3233eb30
@BillmemberId_3=5cad9bfa-d4a9-430a-ac48-ffb2611039d3

### PATCH selected Split-method      PATCH/split/:billId/split-method
PATCH {{Base_URL}}/split/{{BillId_3}}/split-method
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "splitMethod":"ROULETTE"
}

### Get Bill for join
GET {{Base_URL}}/jbill/{{BillId}}/join
Authorization: Bearer {{Token}}


### PATCH select member for roulette
PATCH {{Base_URL}}/roulette/{{BillId_3}}/members/{{BillmemberId_3}}/eligibility
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "eligible": true
}

### Spin Roulette          POST/roulette/:billId/spin
POST {{Base_URL}}/roulette/{{BillId_3}}/spin
Authorization: Bearer {{Token}}


##############################

Complete Bill

PATCH {{Base_URL}}/payment/{{BillId}}/complete
Authorization: Bearer {{Token}}

