@Base_URL=http://localhost:8808/api
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MmM2YjlkYy05NmJiLTRiM2QtOTliNS05NDcyNWQ4NzJiZjMiLCJsaW5lVXNlcklkIjoiVTJiNDkyMDgxMGYxMDYxYzEwMWUyYWU3NWQ1ZDhmYTYzIiwiZGlzcGxheU5hbWUiOiJwYXNpdCIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vcHJvZmlsZS5saW5lLXNjZG4ubmV0LzBoLWwycDZiYTVja01mQ1cxMTFQY01mVzlaY1NrOGVDdFJZMjlwSWk1Y0tYQXFiREVkTlQ4X0lDTmFLeWNxTURFVFptYzZMSGhlTFhvOVdreGdOeHBLVFgxeFZoTkxiWDFvTW1wVlFtTUlRbmRtY1ZRU1hTdFpmMjV6S1FWQVJ6QVFaeHhUWDJOclhBbEJmbnhEVVRGaFdYSVZTQ3RXVUZ4IiwiaWF0IjoxNzg5MzE2MjQwLCJleHAiOjE3OTA1MjU4NDB9.DA-BC1bL7pYM8idp9R16ZFkAZAkG34aYqBen7gO7704
@LineUserId=U2b4920810f1061c101e2ae75d5d8fa63
@UserId=82c6b9dc-96bb-4b3d-99b5-94725d872bf3
@BillId=8af622c3-510b-4171-a237-a94cb19add60


@Token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OWVhZGI1MC0xMjQ0LTQ4ZDgtOTBkYS1iMDE1NmJmNTYxNmMiLCJsaW5lVXNlcklkIjoiVEVTVC1VU0VSLTAxMCIsImRpc3BsYXlOYW1lIjoiQm9iYnkxMCIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vZXhhbXBsZTIuY29tL2F2YXRhci5wbmciLCJpYXQiOjE3ODkzMTYwNjYsImV4cCI6MTc5MDUyNTY2Nn0.fTTS76n-PIpA_AYIScthMXVDdHIR5mKLBUkBTo746Dc
@LineUserId2=TEST-USER-010
@UserId2=59eadb50-1244-48d8-90da-b0156bf5616c

@Token3=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjA2YTYyNS02NzRjLTRmNzQtYTk2My0yYTlhYTVkNTg4M2IiLCJsaW5lVXNlcklkIjoiVEVTVC1VU0VSLTAxMSIsImRpc3BsYXlOYW1lIjoiQm9iYnkxMSIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vZXhhbXBsZTIuY29tL2F2YXRhci5wbmciLCJpYXQiOjE3ODkzMTYzMzAsImV4cCI6MTc5MDUyNTkzMH0.sWAfOWpa9RLorFVnNdKYDuFA_X1dHvUEIyX09Zj4I_0
@LineUserId3=TEST-USER-011
@UserId3=6206a625-674c-4f74-a963-2a9aa5d5883b


@PaymentSlipId=49d4da1a-6c64-4dc9-8d8e-d058fafec427


### Test Api
GET http://localhost:8808


### Register-Line   POST/auth/test-register
POST {{Base_URL}}/auth/test-register
Content-Type: application/json

{
  "lineUserId":"TEST-USER-011",
  "displayName":"Bobby11",
  "profileImage":"https://example2.com/avatar.png",
  "email":"Addy11@mail.com",
  "birthDay":"1995-09-06",
  "qrPayment":"",
  "promptpay":"0023456711"
}

### Test Login   POST/auth/test-login
POST {{Base_URL}}/auth/test-login
Content-Type: application/json

{
  "lineUserId":"{{LineUserId}}"
}


### Create Bill  POST/bills
POST {{Base_URL}}/bills/
Authorization: Bearer {{Token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="billName"

Test Restaurant
--boundary
Content-Disposition: form-data; name="receiptFile"; filename="Receipt.png"
Content-Type: image/png

< C:\Pasit\CCW1\WongLao\Backend\uploads\receipts\Receipt.png
--boundary--



###  OCR Receipt xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx not use xxxxxxxxxxxx
POST {{Base_URL}}/ocr/receipt
Content-Type: application/json

{
    "imagePath":"./uploads/receipts/Receipt.png"
}

### OCR Seve Bill status Checking   xxxxxxxxxxxxxxxx not use xxxxxxxxxxxx
POST {{Base_URL}}/ocr/bill/{{BillId}}
Content-Type: application/json

{"shopName": "บริษัท ร้านอาหาร จำกัด",
    "branch": "สาขา 00001",
    "receiptNumber": "ธ12-67-0119-00001",
    "date": "14/3/2566",
    "time": "20:36:32",
    "customerName": "เอกวัฒน์ ปูคำ",
    "items": [
      {
        "name": "ผัดเผ็ดเนื้อ",
        "quantity": 1,
        "unitPrice": 189,
        "totalPrice": 189
      },
      {
        "name": "ปลาทอดน้ำปลา",
        "quantity": 1,
        "unitPrice": 249,
        "totalPrice": 249
      },
      {
        "name": "ปลาทับทิมเพิ่ม",
        "quantity": 1,
        "unitPrice": 50,
        "totalPrice": 50
      },
      {
        "name": "ต้มยำทะเลรวม",
        "quantity": 1,
        "unitPrice": 249,
        "totalPrice": 249
      },
      {
        "name": "แสงโสม (กลม)",
        "quantity": 1,
        "unitPrice": 389,
        "totalPrice": 389
      },
      {
        "name": "น้ำเปล่า",
        "quantity": 2,
        "unitPrice": 20,
        "totalPrice": 40
      },
      {
        "name": "โซดา",
        "quantity": 2,
        "unitPrice": 29,
        "totalPrice": 58
      },
      {
        "name": "น้ำแข็ง",
        "quantity": 1,
        "unitPrice": 29,
        "totalPrice": 29
      },
      {
        "name": "เอ็นไก่ทอด 1+1",
        "quantity": 2,
        "unitPrice": null,
        "totalPrice": 129
      }
    ],
    "subtotal": 1382,
    "vat": 103.56,
    "totalAmount": 1583
}


### OCR Bill by billId        POST/ocr/bill/:billId
POST {{Base_URL}}/ocr/bill/{{BillId}}
Authorization: Bearer {{Token}}

### Verify bill           PUT/bills/:billId/verify
PUT {{Base_URL}}/bills/{{BillId}}/verify
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "shopName": "บริษัท ร้านอาหาร จำกัด",
  "totalAmount": 1583
}

### JoinBill        POST/jbill/:billId/join
POST {{Base_URL}}/jbill/{{BillId}}/join
Authorization: Bearer {{Token3}}


### Get Bill for join
GET {{Base_URL}}/jbill/{{BillId}}/join
Authorization: Bearer {{Token}}



### PATCH selected Split-method      PATCH/split/:billId/split-method
PATCH {{Base_URL}}/split/{{BillId}}/split-method
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "splitMethod":"EQUAL"
}

#########################################################################
### Select share-method
POST {{Base_URL}}/split/{{BillId}}/equal
Authorization: Bearer {{Token}}

### Get my payment/me       GET/payment/:billId/me
GET {{Base_URL}}/payment/{{BillId}}/me
Authorization: Bearer {{Token}}


### Upload Payment Slip
POST {{Base_URL}}/payment/{{BillId}}/slip
Authorization: Bearer {{Token}}
Content-Type: multipart/form-data; boundary=----WongLaoBoundary

------WongLaoBoundary
Content-Disposition: form-data; name="proofImage"; filename="slip.jpg"
Content-Type: image/jpeg

< C:\Pasit\CCW1\WongLao\Backend\uploads\slip\09435DA7-D68D-4FCD-8485-FD18D8788A57.jpg
------WongLaoBoundary--

### Get Pending Payment Slips    GET/payment/:billId/pending
GET {{Base_URL}}/payment/{{BillId}}/pending
Authorization: Bearer {{Token}}


###GET All bill UnPaid
GET {{Base_URL}}/payment/summary?page=1&limit=5
Authorization: Bearer {{Token}}

### Verify Payment Slip
PATCH {{Base_URL}}/payment/slip/{{PaymentSlipId}}/verify
Authorization: Bearer {{Token}}

